  - alias: Reset garagePIR state
    hide_entity: true
    initial_state: 'on'
    trigger:
    - platform: state
      entity_id: binary_sensor.sensor
      from: 'off'
      to: 'on'
      for:
        seconds: 5
    action:
    - service: mqtt.publish
      data:
        topic: tele/RFBridge/RESULT
        payload: DBAFE9off