homeassistant:
  name: Home
  latitude: 0
  longitude: 0
  elevation: 0
  unit_system: metric
  time_zone: UTC
  customize: !include customize.yaml

introduction:
frontend:
config:
updater:
discovery:
history:
logbook:
map:
sun:
sensor:
  - platform: yr

tts:
  - platform: google

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
