homeassistant:
  name: Casa
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 4.2
  unit_system: metric
  time_zone: Europe/Lisbon
  customize: !include customize.yaml

introduction:
frontend:
config:
updater:
discovery:
history:
logbook:
map:
sun:
tts:
  - platform: google

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

panel_iframe: !include includes/iframe.yaml
zone: !include includes/zones.yaml