homeassistant:
  name: Casa
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 4.2
  unit_system: metric
  time_zone: Europe/Lisbon
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

lovelace: 
  mode: yaml

map:
config:
logbook:
sun: 
discovery:
history: !include includes/history.yaml

#Core stuff
http: !include includes/http.yaml
frontend: !include includes/frontend.yaml
automation: !include automations.yaml
script: !include scripts.yaml
zone: !include includes/zones.yaml
tts: !include includes/tts.yaml
influxdb: !include includes/influxdb.yaml
panel_iframe: !include includes/iframe.yaml
mqtt: !include includes/mqtt.yaml
sensor: !include includes/sensor.yaml
weather: !include includes/weather.yaml
binary_sensor: !include includes/binary_sensor.yaml
device_tracker: !include includes/device_tracker.yaml
input_boolean: !include includes/input_boolean.yaml
light: !include includes/light.yaml
group: !include includes/group.yaml
switch: !include includes/switch.yaml
digital_ocean: !include includes/digital_ocean.yaml
media_player: !include includes/media_player.yaml
ffmpeg: !include includes/ffmpeg.yaml
camera: !include includes/camera.yaml
script: !include_dir_merge_named includes/scripts
