homeassistant:
  name: Casa
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 4.2
  unit_system: metric
  time_zone: Europe/Lisbon
  customize: !include_dir_merge_named includes/customize
  whitelist_external_dirs:
     - !secret publictempfolder

map:
config:
logbook:
sun: 

group: !include_dir_merge_named includes/group
script: !include_dir_merge_named includes/scripts
shell_command: !include_dir_merge_named includes/shell_command

zone: !include includes/core/zones.yaml
history: !include includes/core/history.yaml
recorder: !include includes/core/recorder.yaml
frontend: !include includes/core/frontend.yaml
updater: !include includes/core/updater.yaml
http: !include includes/core/http.yaml
logger: !include includes/core/logger.yaml
tts: !include includes/core/tts.yaml
notify: !include includes/core/notify.yaml

automation: !include_dir_merge_list includes/automations

ffmpeg: !include includes/components/ffmpeg.yaml
google_assistant: !include includes/components/google_assistant.yaml
telegram_bot: !include includes/components/telegram_bot.yaml
mqtt: !include includes/components/mqtt.yaml
switch: !include includes/switch.yaml
sensor: !include includes/sensor.yaml
light: !include includes/light.yaml
camera: !include includes/camera.yaml
device_tracker: !include includes/device_tracker.yaml
media_player: !include includes/media_player.yaml
binary_sensor: !include includes/binary_sensor.yaml
input_boolean: !include includes/input_boolean.yaml
climate: !include includes/climate.yaml
weather: !include includes/weather.yaml
scene: !include includes/scenes/scenes.yaml

digital_ocean:
  access_token: !secret digital_ocean

panel_iframe:
 nodered:
   title: 'Node-Red'
   icon: 'mdi:basket-unfill'
   url: https://ptorrezao.duckdns.org:1880