
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

recorder:
  purge_keep_days: 15
  db_url: !secret db_connectionString

api:
device_tracker: !include includes/device_tracker.yaml
speedtestdotnet: 
octoprint: !include includes/octoprint.yaml
panel_iframe: !include includes/iframe.yaml
light: !include_dir_merge_list includes/lights/
switch: !include_dir_merge_list includes/switch/
sensor: !include_dir_merge_list includes/sensor/
owntracks: !include includes/owntracks.yaml
duckdns: !include includes/duckdns.yaml
geo_location: !include includes/geo_location.yaml
vacuum: !include includes/vacuum.yaml
camera: !include includes/camera.yaml
ffmpeg: