homeassistant:
  name: Casa
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 4.2
  unit_system: metric
  time_zone: Europe/Lisbon
  customize: !include_dir_merge_named includes/customize

map:
config:
logbook:
sun: 

zone: !include includes/core/zones.yaml
history: !include includes/core/history.yaml
group: !include_dir_merge_named includes/core/group
recorder: !include includes/core/recorder.yaml
frontend: !include includes/core/frontend.yaml
updater: !include includes/core/updater.yaml
http: !include includes/core/http.yaml
logger: !include includes/core/logger.yaml
tts: !include includes/core/tts.yaml
scene: !include includes/core/scenes.yaml
automation: !include includes/core/automations.yaml
script: !include includes/core/scripts.yaml
notify: !include includes/core/notify.yaml

ffmpeg: !include includes/components/ffmpeg.yaml
google_assistant: !include includes/components/google_assistant.yaml
telegram_bot: !include includes/components/telegram_bot.yaml
mqtt: !include includes/components/mqtt.yaml


panel_custom: !include includes/panel_custom.yaml

sensor: !include includes/sensor.yaml
light: !include includes/light.yaml
camera: !include includes/camera.yaml
device_tracker: !include includes/device_tracker.yaml
media_player: !include includes/media_player.yaml
input_text: !include includes/input_text.yaml
binary_sensor: !include includes/binary_sensor.yaml
input_boolean: !include includes/input_boolean.yaml
input_number: !include includes/input_number.yaml