homeassistant:
  name: Casa
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 4.2
  unit_system: metric
  time_zone: Europe/Lisbon
  customize: !include customize.yaml

map:
config:
logbook:
sun: 
discovery:
history:

#Core stuff
http: !include includes/http.yaml
group: !include_dir_merge_named includes/group
frontend: !include includes/frontend.yaml
automation: !include automations.yaml
script: !include scripts.yaml
zone: !include includes/zones.yaml
tts: !include includes/tts.yaml
influxdb: !include includes/influxdb.yaml
 

panel_iframe: !include includes/iframe.yaml
mqtt: !include includes/mqtt.yaml
sensor: !include includes/sensor.yaml