
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

recorder:
  purge_keep_days: 15
  db_url: !secret db_connectionString

device_tracker:
  - platform: luci
    host: openwrt
    username: !secret OpenWrt_Username 
    password: !secret OpenWrt_Password

octoprint: 
  - host: octopi
    api_key: !secret octoprintAPIKey
    name: Creality Ender 3
    number_of_tools: 2
    bed: true

light: !include_dir_merge_list includes/lights/
switch: !include_dir_merge_list includes/switch/
sensor: !include_dir_merge_list includes/sensor/