version: '3.1'

services:
  homeassistant:
    image: homeassistant/home-assistant:latest
    restart: always
    ports:
      - "8123:8123"
    volumes:
      - ha_config:/config
      - /etc/letsencrypt/:/ssl
  mqtt:
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"

  adminer:
    image: adminer
    restart: always
    deploy:
      replicas: 0
    ports:
      - "8080:8080"

  mysql:
    image: mysql:5.6
    restart: always
    deploy:
      placement:
        constraints:
          - node.role == manager
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PWD}"
    volumes:
      - mysql:/var/lib/mysql
      
volumes:
  ha_config:
  mysql: