resources:
  - url: /local/plan-coordinates.js?v=1
    type: js
  - url: /local/mini-media-player-bundle.js?v=0.9.8
    type: module

title: Casa 
views:
  - title: Hall
    path: default_view
    icon: 'mdi:home'
    badges: []
    cards: 
    - type: entity-filter
      show_empty: false
      entities:
        - entity: device_tracker.pedro_aquaris
          name: Pedro
        - entity: device_tracker.ana_bq
          name: Ana
        - entity: input_boolean.houseguest
          name: Convidados
      state_filter:
        - home
        - "on"
      card: 
        type: glance
        show_state: false
        title: Em casa  
    - type: vertical-stack
      cards:
      - type: horizontal-stack
        cards:
        - title: Escritório
          type: picture-glance
          aspect_ratio: 16x9
          entities:
            - group.office_ligths
          state_image:
            "On": /local/office_photo_on.jpg
            "Off": /local/office_photo_off.jpg
          entity: group.office
          image: /local/office_photo_on.jpg
          hold_action: 
            action: navigate
            navigation_path: /lovelace/4/
          tap_action: 
            action: toggle
        - title: Sala de Estar
          type: picture-glance
          aspect_ratio: 16x9
          entities:
            - group.livingroom_ligths
          state_image:
            "On": /local/livingroom_photo_on.jpg
            "Off": /local/livingroom_photo_off.jpg
          entity: group.livingroom
          image: /local/livingroom_photo_on.jpg
          hold_action: 
            action: navigate
            navigation_path: /lovelace/1/
          tap_action: 
            action: toggle
      - type: horizontal-stack
        cards:
        - title: Quarto Madalena
          type: picture-glance
          aspect_ratio: 16x9
          entities:
            - group.nursery_ligths
          state_image:
            "On": /local/nursery_photo_on.jpg
            "Off": /local/nursery_photo_off.jpg
            "unknown": /local/nursery_photo_off.jpg
          entity: group.nursery
          image: /local/nursery_photo_off.jpg
          hold_action: 
            action: navigate
            navigation_path: /lovelace/3/
          tap_action: 
            action: toggle
        - title: Quarto Pedro & Ana
          type: picture-glance
          aspect_ratio: 16x9
          entities:
            - group.bedroom_ligths
          state_image:
            "On": /local/bedroom_photo_on.jpg
            "Off": /local/bedroom_photo_off.jpg
            "unknown": /local/bedroom_photo_off.jpg
          entity: group.bedroom
          image: /local/bedroom_photo_on.jpg
          hold_action: 
            action: navigate
            navigation_path: /lovelace/2/
          tap_action: 
            action: toggle
      - type: horizontal-stack
        cards:
        - title: Cozinha
          type: picture-glance
          aspect_ratio: 16x9
          entities:
            - group.kitchen_lights
          state_image:
            "On": /local/kitchen_photo_on.jpg
            "Off": /local/kitchen_photo_off.jpg
            "unknown": /local/kitchen_photo_off.jpg
          entity: group.kitchen
          image: /local/kitchen_photo_on.jpg
          hold_action: 
            action: navigate
            navigation_path: /lovelace/5/
          tap_action: 
            action: toggle     
        - title: Garagem
          type: picture-glance
          aspect_ratio: 16x9
          entities:
            - group.garage_lights
          state_image:
            "On": /local/garage_photo_on.jpg
            "Off": /local/garage_photo_off.jpg
            "unknown": /local/garage_photo_off.jpg
          entity: group.garage
          image: /local/garage_photo_off.jpg
          hold_action: 
            action: navigate
            navigation_path: /lovelace/6/
          tap_action: 
            action: toggle  
        - title: Sotão
          type: picture-glance
          aspect_ratio: 16x9
          entities:
            - group.nursery_lights
          state_image:
            "On": /local/attic_photo_on.jpg
            "Off": /local/attic_photo_off.jpg
            "unknown": /local/attic_photo_off.jpg
          entity: group.attic
          image: /local/attic_photo_on.jpg
          hold_action: 
            action: navigate
            navigation_path: /lovelace/7/
          tap_action: 
            action: toggle     
    - type: markdown
      title: WIFI
      content: >
        SSID/Network Name: **ZON-Pedro & Ana**

        Password: **f9ffa4cf33ec**

        Network Type: **WPA**   
    - type: map
      aspect_ratio: 16x9
      default_zoom: 15
      entities:
      - device_tracker.ana_bq
      - zone.home
      - device_tracker.pedro_aquaris
    - type: horizontal-stack
      cards:
        - type: vertical-stack
          cards:
          - type: weather-forecast
            entity: weather.ipma
            aspect_ratio: 62%
          - type: iframe
            url: !secret weatherUrl
            aspect_ratio: 38%   
  - title: Sala de Estar
    cards: 
    - type: entities
      title: Luzes
      show_header_toggle: false
      entities:
        - light.living_room_cabinet
        - switch.christmas_lights
    - type: entities
      title: Media Center
      show_header_toggle: false
      entities:
        - entity: binary_sensor.lg_tv_5600
          icon: mdi:television-classic
        - entity: media_player.main_tv
          type: custom:mini-media-player
          artwork: cover
          group: true
          hide_volume: true
    badges: []
    icon: 'mdi:sofa'
    theme: Backend-selected
  - title: Quarto 
    cards:     
    - type: entities
      title: Luzes
      show_header_toggle: false
      entities:
        - group.bedroom_ligths
    badges: []
    icon: 'mdi:hotel'
  - title: Quarto Madalena
    cards:     
    - type: entities
      title: Luzes
      show_header_toggle: false
      entities:
        - light.nursery_light
    - type: picture-glance
      title: Camera
      entities:
        - camera.baby_room
      camera_image: camera.baby_room
    badges: []
    icon: 'mdi:baby-buggy'
  - title: Escritório
    cards:
    - type: conditional
      conditions:
        - entity: binary_sensor.internet_check
          state: "on"
      card:
        type: entities
        title: Web Stuff
        show_header_toggle: false
        entities:
        - entity: sensor.ptorrezaoduckdnsorg
          name: IP
          secondary_info: last-changed
        - entity: sensor.speedtest_upload
          name: Upload Speed
        - entity: sensor.speedtest_download
          name: Download Speed
        - entity: sensor.ssl_ptorrezaoduckdnsorg
          name: Certificado SSL
    - type: horizontal-stack
      cards:
        - type: sensor
          entity: sensor.temperatura_office
          name: Temperatura
          graph: none
        - type: sensor
          entity: sensor.humidade_office
          name: Humidade
          graph: none
    - type: entities
      title: Lights
      show_header_toggle: false
      entities:
        - light.office_ceiling_light
        - light.office_desk_light
        - light.office_rgb
        - light.office_lego_light
    - type: entities
      title: Smart Plugs
      show_header_toggle: false
      entities:
        - switch.remote_switch_1
        - switch.remote_switch_2
    - type: vertical-stack
      cards:
      - type: entities
        title: IT Devices (Networking/Infrastructure)
        show_header_toggle: false
        entities:
          - entity: binary_sensor.openwrt
            name: OpenWrt (Router)
            icon: mdi:router-wireless
          - entity: binary_sensor.tlsg108e
            name: TL-SG108E (Smart Switch)
            icon: mdi:switch
          - entity: binary_sensor.re200
            icon: mdi:access-point
            name: RE200 (Range Extender)
          - type: divider
          - entity: binary_sensor.epsond11b70
            name: Printer
            icon: mdi:printer
          - type: divider
          - entity: binary_sensor.aphrodite
            name: Aphrodite
            icon: mdi:server-security
          - entity: binary_sensor.ares
            icon: mdi:server-security
            name: Ares
          - entity: binary_sensor.dtoffice
            name: DT-Office
            icon: mdi:desktop-classic
          - type: divider
          - entity: binary_sensor.armclusternode01
            name: ArmCluster-Node01
            icon: mdi:hexagon-slice-1
          
      - type: entities
        title: IT Devices (Smart Home/Entertainment)
        show_header_toggle: false
        entities:
          - entity: binary_sensor.playstation
            name: Playstation
            icon: mdi:gamepad-variant
          - entity: binary_sensor.chromecastofficetv
            name: Chromecast Office TV
            icon: mdi:television-classic
          - entity: media_player.office_tv_2
            type: custom:mini-media-player
            artwork: cover
            group: true
            hide_volume: true
          - entity: binary_sensor.hisense_h39n2110c
            name: Office TV
            icon: mdi:television-classic
          - type: divider
          - entity: binary_sensor.googlehome
            name: Google Home
            icon: mdi:google-home
          - entity: binary_sensor.broadlink
            name: BroadLink
            icon: mdi:remote
    - entity: media_player.escritorioghome
      type: custom:mini-media-player
      name: Google Home 
      hide_controls: true
      artwork: cover
      show_tts: google
      power_color: true
    - entity: media_player.officetv
      type: custom:mini-media-player
      artwork: cover
      hide_volume: true
    icon: 'mdi:network'
  - title: Cozinha 
    icon: 'mdi:knife'
    cards:     
    - type: entities
      title: Luzes
      show_header_toggle: false
      entities:
        - group.kitchen_ligths
  - title: Garage 
    icon: 'mdi:garage-open'
    cards:     
    - type: entities
      title: Luzes
      show_header_toggle: false
      entities:
        - group.garage_ligths
  - title: Sotão 
    cards:     
    - type: entities
      title: Luzes
      show_header_toggle: false
      entities:
        - group.attic_ligths
    icon: 'mdi:home-variant-outline'
  - title: Configurations
    cards: 
    - type: entities
      title: Groups
      show_header_toggle: false
      entities:
        - group.all_devices
        - group.all_lights
        - group.all_switches
        - group.all_scripts
        - input_boolean.home_occupied
        - binary_sensor.ipcam01
        - media_player.officetv
    - type: entities
      title: Office Scripts 
      show_header_toggle: false
      entities:
        - script.turnofftv
        - script.turnontv
    badges: 
      - binary_sensor.internet_check
      - binary_sensor.workday_sensor
      - binary_sensor.chromecastmaintv
      - sun.sun
    icon: 'mdi:wrench'
  - title: Relatórios
    cards: []
    badges: []
    icon: 'mdi:marker-check'
  - title: Floorplan
    panel: true
    icon: 'mdi:floor-plan'
    badges: []
    cards: 
    - type: vertical-stack
      cards: 
        - type: custom:plan-coordinates  
        - type: picture-elements
          image: /local/floorplan.png
          elements:
          - type: state-label
            entity: sensor.temperatura_office
            style:
              top: 37%
              left: 31.5%
              color: "#6b6a6a"
              font-size: 0.8vw
          - type: state-label
            entity: sensor.humidade_office
            style:
              top: 40%
              left: 31.5%
              color: "#6b6a6a"
              font-size: 0.8vw
          - type: image
            entity: weather.ipma
            image: /local/weather_sun.png
            state_image:
              'clear-night': /local/weather_moon.png
              'cloudy': /local/weather_cloudy.png
              'fog': /local/weather_fog.png
              'hail': /local/weather_snow.png
              'lightning': /local/weather_lightning.png
              'lightning-rainy': /local/weather_lightning.png
              'partlycloudy': /local/weather_cloudy.png
              'pouring': /local/weather_drop.png
              'rainy': /local/weather_drop.png
              'snowy': /local/weather_snow.png
              'snowy-rainy': /local/weather_snow.png
              'sunny': /local/weather_sun.png
              'windy': /local/weather_wind.png
              'windy-variant': /local/weather_wind.png
            style:
              top: 81.1%
              left: 41.2%
              width: 1.5vw
          - type: image
            entity: binary_sensor.internet_check
            image: /local/internet_off.png
            state_image:
              'on': /local/internet_on.png
              'off': /local/internet_off.png
            style:
              top: 85.4%
              left: 41.2%
              width: 1.5vw
          - type: image
            entity: input_boolean.houseguest
            image: /local/guest_on.png
            state_image:
              'on': /local/guest_on.png
              'off': /local/guest_off.png
            style:
              top: 89.4%
              left: 41.2%
              width: 1.5vw
          - type: image
            entity: input_boolean.home_occupied
            image: /local/guest_on.png
            state_image:
              'on': /local/home_on.png
              'off': /local/home_off.png
            style:
              top: 93.4%
              left: 41.2%
              width: 1.5vw