- platform: group
  name: Nursery Lights
  entities:
    - light.nursery_bedlight
    - light.yeelight_color_0x000000000531e709
    
- platform: mqtt
  name: "Nursery BedLight"
  state_topic: "nursery-bedlight/stat/POWER1"
  command_topic: "nursery-bedlight/cmnd/Power"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
  unique_id: "nursery_sensor"
  brightness_scale: 100
  brightness_command_topic: "nursery-bedlight/cmnd/DIMMER"
  brightness_state_topic: "nursery-bedlight/stat/RESULT"
  brightness_value_template: "{{ value_json.Dimmer }}"
  rgb_command_topic: "nursery-bedlight/cmnd/COLOR"
  rgb_command_template: "{{ '%02x%02x%02x' | format(red, green, blue)}}" 
  rgb_state_topic: "nursery-bedlight/stat/RESULT"
  rgb_value_template: "{{ value_json.Color[0:2] | int(base=16) }},{{ value_json.Color[2:4] | int(base=16) }},{{ value_json.Color[4:6] | int(base=16) }}"

