- platform: mqtt
  name: "Xmas Lights"
  state_topic: "xmas_lights/stat/POWER"
  command_topic: "xmas_lights/cmnd/Power"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
  unique_id: "xmas_tree_lights"

- platform: mqtt
  name: "Cabinet Lights"
  state_topic: "cabinet_light/stat/POWER"
  command_topic: "cabinet_light/cmnd/Power"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
  unique_id: "livingroom_cabinet"
