- platform: mqtt
  name: "Office Ceiling Light"
  state_topic: "officelight/stat/POWER1"
  command_topic: "officelight/cmnd/Power"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
  unique_id: "office_ceiling_light"

- platform: mqtt
  name: "Office Desktop Light"
  state_topic: "officelight-desk/stat/POWER"
  command_topic: "officelight-desk/cmnd/Power"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
  unique_id: "office_desktop_light"