- alias: "[System] - Time to Bed"
  id: '1010'
  trigger:
    platform: state
    entity_id: input_boolean.bedtime
    from: 'off'
    to: 'on'
  action:
  -  service: light.turn_off
     entity_id: group.card_lightsoffice
  -  service: media_player.turn_off
     entity_id: media_player.office_tv

- alias: "[System] - Reset Time To Bed"
  id: '1011'
  trigger:
   platform: sun
   event: sunrise
   offset: '+00:00:00'
  condition:  
    condition: and
    conditions: 
      - condition: state
        entity_id: input_boolean.bedtime
        state: 'on'
  action:
  - service: input_boolean.turn_off 
    entity_id: input_boolean.bedtime

- alias: "[System] - Tentativa de Ataque Home Assistant"
  trigger:
    - platform: state
      entity_id: persistent_notification.httplogin
  condition:
    - condition: template
      value_template: "{{ trigger.to_state.state != 'None' }}"
  action:
    - service: notify.telegram_pedro
      data_template:
        title: "Tentativa de Ataque Home Assistant"
        message: "{{ states.persistent_notification.httplogin.attributes.message }}"
