- alias: "[Work] - Check if You Still At Home At 7h30"
  id: '5000'
  trigger:
    - platform: time
      at: '07:30:00'
  condition:  
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
    - condition: state
      entity_id: 'device_tracker.pedro_aquaris'
      state: 'home'
    - condition: state
      entity_id: input_boolean.onvacations
      state: 'off'
  action:
  - service: light.turn_on
    data:
       entity_id: light.office_lego_light
       color_name: green
###
- alias: "[Work] - Check if You Still At Home At 7h50"
  id: '5001'
  trigger:
    - platform: time
      at: '07:50:00'
  condition:  
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
    - condition: state
      entity_id: 'device_tracker.pedro_aquaris'
      state: 'home'
    - condition: state
      entity_id: input_boolean.onvacations
      state: 'off'
  action:
  - service: light.turn_on
    data:
       entity_id: light.office_lego_light
       color_name: yellow
       
###
- alias: "[Work] - Check if You Still At Home At 8h15"
  id: '5002'
  trigger:
    - platform: time
      at: '08:15:00'
  condition:  
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
    - condition: state
      entity_id: 'device_tracker.bq_pedro'
      state: 'home'
    - condition: state
      entity_id: input_boolean.onvacations
      state: 'off'
  action:
  # - service: notify.gmail_smtp
    # data: 
     # title: "*Atrasado*"
     # message: "Mexe-te crlh vais chegar atrasado!! ETA para Escritório: {{ states.sensor.eta_pedro.state }}mins"
  - service: light.turn_on
    data:
       entity_id: light.office_lego_light
       color_name: red