- platform: template
  sensors:
    eta_pedro:
     friendly_name: "ETA"
     unit_of_measurement: "min"
     value_template: >-
        {% if is_state('device_tracker.pedro_cppedrohome', 'home') %}
            {% if now().isoweekday() | float < 6 %}
            {{ states("sensor.pedrotowork") }}
            {% else %}
            0
            {% endif %}
        {% else %}
            {{ states("sensor.pedrotohome") }}
        {% endif %}