- platform: mqtt
  state_topic: "office_sensor/tele/SENSOR"
  value_template: "{{ value_json.BMP280.Temperature }}"
  name: "Temperatura Office"
  qos: 0
  unit_of_measurement: "°C"
  unique_id: "temp_office"

- platform: mqtt
  state_topic: "3dprinter/tele/SENSOR"
  value_template: "{{ value_json.ENERGY.Total }}"
  name: "3d Printer PowerPlug Total"
  qos: 0
  unit_of_measurement: "Kwh"
  unique_id: "3dprinterpowerplug_total"

- platform: mqtt
  state_topic: "3dprinter/tele/SENSOR"
  value_template: "{{ value_json.ENERGY.Today }}"
  name: "3d Printer PowerPlug Today"
  qos: 0
  unit_of_measurement: "Kwh"
  unique_id: "3dprinterpowerplug_today"

- platform: mqtt
  state_topic: "3dprinter/tele/SENSOR"
  value_template: "{{ value_json.ENERGY.Voltage }}"
  name: "3d Printer PowerPlug Voltage"
  qos: 0
  unit_of_measurement: "V"
  unique_id: "3dprinterpowerplug_voltage"

- platform: mqtt
  state_topic: "3dprinter/tele/SENSOR"
  value_template: "{{ value_json.ENERGY.Current }}"
  name: "3d Printer PowerPlug Current"
  qos: 0
  unit_of_measurement: "Amp"
  unique_id: "3dprinterpowerplug_current"