- platform: mqtt
  state_topic: "3dprinter/tele/SENSOR"
  value_template: "{{ value_json.ENERGY.Total }}"
  name: "3d Printer PowerPlug Total"
  qos: 0
  unit_of_measurement: "Kwh"
  unique_id: "3dprinterpowerplug_total"

- platform: mqtt
  state_topic: "3dprinter/tele/SENSOR"
  value_template: "{{ value_json.ENERGY.Today }}"
  name: "3d Printer PowerPlug Today"
  qos: 0
  unit_of_measurement: "Kwh"
  unique_id: "3dprinterpowerplug_today"

- platform: mqtt
  state_topic: "3dprinter/tele/SENSOR"
  value_template: "{{ value_json.ENERGY.Voltage }}"
  name: "3d Printer PowerPlug Voltage"
  qos: 0
  unit_of_measurement: "V"
  unique_id: "3dprinterpowerplug_voltage"

- platform: mqtt
  state_topic: "3dprinter/tele/SENSOR"
  value_template: "{{ value_json.ENERGY.Current }}"
  name: "3d Printer PowerPlug Current"
  qos: 0
  unit_of_measurement: "Amp"
  unique_id: "3dprinterpowerplug_current"

- platform: template
  sensors:
    3dprinterpowerplugcost:
      friendly_name: "€ Electricidade"
      unit_of_measurement: '€'
      value_template: "{{  (float(states('sensor.3d_printer_powerplug_total')) * float(states('input_number.preco_electricidade'))) | round(2)}} "

