- platform: mqtt
  state_topic: "office_sensor/tele/SENSOR"
  value_template: "{{ value_json.BMP280.Temperature }}"
  name: "Temperatura Office"
  qos: 0
  unit_of_measurement: "°C"
  unique_id: "temp_office"
