- platform: template
  sensors:
    openwrt:
     friendly_name: "Open WRT"
     value_template: >-
        {% if is_state('device_tracker.openwrthome', 'home') %}
          Ligado
        {% else %}
          Desligado
        {% endif %}