- platform: template
  sensors:
    playstation:
      friendly_name: "PS4"
      value_template: >-
        {% if is_state('device_tracker.ps4home', 'home') %}
          Ligada
        {% else %}
          Desligada
        {% endif %}