- platform: mqtt
  name: "Remote Switch"
  state_topic: "remoteSwitch/stat/POWER"
  command_topic: "remoteSwitch/cmnd/Power"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
  unique_id: "remote_switch"

- platform: mqtt
  name: "Ender 3 Remote Switch"
  state_topic: "3dprinter/stat/POWER"
  command_topic: "3dprinter/cmnd/Power"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
  unique_id: "bw_shp2_01"
