###
# No Body Home
###
- alias: "[Automation] - No Body Home"
  id: '1114581592811'
  trigger:
    platform: state
    entity_id: group.card_family
    from: 'home'
    to: 'not_home'
  condition:  
    condition: and
    conditions: 
      - condition: state
        entity_id: 'input_boolean.workfromhome_mode'
        state: 'off'
  action:
  - service: script.turn_on
    entity_id: script.shutdownhome