###
# Sleep Mode Trigger
###
- alias: "[Mode Triggers] - Sleep Mode Trigger"
  id: '1514281697813'
  trigger:
    platform: state
    entity_id: input_boolean.sleep_mode
    to: 'on'
  action:
  - service: script.turn_on
    entity_id: script.sleep
    
- alias: "[Mode Triggers] - Reset Sleep Mode"
  id: '1514281697814'
  trigger:
    platform: time
    at: '7:00:00'
  action:
  - service: input_boolean.turn_off 
    entity_id: input_boolean.sleep_mode
    
- alias: "[Mode Triggers] - Set Remote Work Mode To On"
  id: '1516281391814'
  trigger:
    platform: state
    entity_id: input_boolean.workfromhome_mode
    to: 'on'
  action:
  - service: script.turn_on 
    entity_id: script.radio

- alias: "[Mode Triggers] - Set Remote Work Mode To Off"
  id: '1516281391814'
  trigger:
    platform: state
    entity_id: input_boolean.workfromhome_mode
    to: 'off'
  action:
  - service: script.turn_off 
    entity_id: script.radio