###
# Notify if Ip Changes
###
- alias: "[System] - Public IP Has Changed"
  id: '1514281697811'
  trigger:
    platform: state
    entity_id: sensor.ptorrezaoduckdnsorg
  action:
  - service: notify.allNotifiers
    data_template: 
      message: "IP changed: {{ trigger.from_state.state }} → {{ trigger.to_state.state }}"