###
# Check if You Still At Home At 7h30
###
- alias: "[Work] - Check if You Still At Home At 7h30"
  id: '1514281297812'
  trigger:
    - platform: time
      at: '07:30:00'
  condition:  
    condition: and
    conditions: 
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
      - condition: state
        entity_id: 'device_tracker.pedro_cppedrohome'
        state: 'home'
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'off'
  action:
  - service: light.turn_on
    data:
       entity_id: light.office_lego_light
       color_name: green
###
# Check if You Still At Home At 7h50
###
- alias: "[Work] - Check if You Still At Home At 7h50"
  id: '1514281297815'
  trigger:
    - platform: time
      at: '07:50:00'
  condition:  
    condition: and
    conditions: 
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
      - condition: state
        entity_id: 'device_tracker.pedro_cppedrohome'
        state: 'home'
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'off'
  action:
  - service: light.turn_on
    data:
       entity_id: light.office_lego_light
       color_name: yellow
       
###
# Check if You Still At Home At 8h20
###
- alias: "[Work] - Check if You Still At Home At 8h20"
  id: '1514281697812'
  trigger:
    - platform: time
      at: '08:20:00'
  condition:  
    condition: and
    conditions: 
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
      - condition: state
        entity_id: 'device_tracker.pedro_cppedrohome'
        state: 'home'
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'off'
  action:
  - service: notify.telegram
    data: 
     title: "*Atrasado*"
     message: "Mexe-te crlh vais chegar atrasado!! ETA para Escritório: {{ states.sensor.eta_pedro.state }}mins"
  - service: light.turn_on
    data:
       entity_id: light.office_lego_light
       color_name: red