- platform: workday
  country: PT
  excludes : [ sat, sun, holiday ]
- platform: mqtt
  state_topic: dummy/guestWifi/sensor
  name: guestWifi
- platform: mqtt
  state_topic: dummy/floorplan/sensor
  name: Floorplan