- platform: workday
  country: PT
  excludes : [ sat, sun, holiday ]
- platform: ping
  host: 8.8.8.8
  name: Internet Check
  count: 2
- platform: ping
  #host: chromecast-maintv
  host: 192.168.88.156
  name: LG TV 5600
  count: 2
- platform: ping
  #host: EPSOND11B70
  host: 192.168.88.11
  name: EPSOND11B70
- platform: ping
  #host: OpenWrt
  host: 192.168.88.1
  name: OpenWrt
- platform: ping
  #host: OpenWrt
  host: 192.168.88.2
  name: TLSG108E
- platform: ping
  #host: OpenWrt
  host: 192.168.88.3
  name: RE200
- platform: ping
  #host: DT-Office
  host: 192.168.88.30
  name: DT-Office
  count: 2
- platform: ping
  #host: Aphrodite
  host: 192.168.88.20
  name: Aphrodite
  count: 2
- platform: ping
  #host: Aphrodite
  host: 192.168.88.21
  name: Ares
  count: 2  
- platform: ping
  #host: Aphrodite
  host: 192.168.88.25
  name: Arm-Cluster-Node01
  count: 2  
- platform: ping
  #host: Aphrodite
  host: 192.168.88.25
  name: Arm-Cluster-Node01
  count: 2  
- platform: command_line
  command: 'nmap -p 9295 192.168.88.100 | grep "9295/tcp open" | wc -l'
  name: 'Playstation'
  device_class: connectivity
  payload_on: 1
  payload_off: 0
  scan_interval: 30
- platform: ping
  host: 192.168.88.155
  name: Chromecast-Office-TV
  count: 2
  scan_interval: 15
- platform: ping
  host: 192.168.88.150
  name: Google-Home
  count: 2
- platform: ping
  host: 192.168.88.200
  name: Broadlink
  count: 2
- platform: ping
  host: 192.168.88.225
  name: ipcam01
  count: 2
- platform: ping
  host: 192.168.88.155
  name: Hisense H39N2110C
  count: 2
  scan_interval: 30