- platform: mjpeg
  name: OctoPrint
  still_image_url: http://octopi/webcam/?action=snapshot
  mjpeg_url: http://octopi/webcam/?action=stream
- platform: ffmpeg
  name: Baby Room
  input: rtsp://admin:@ipcam01/onvif2