- platform: ffmpeg
  name: Baby Room
  input: !secret babyRoomCameraURL
- platform: generic
  name: 3d Printer
  still_image_url: http://octopi:8080/?action=snapshot
  stream_source: http://octopi:8080/?action=stream