- platform: owntracks
- platform: googlehome
  host: 192.168.88.150    
  rssi_threshold: -100 
  interval_seconds: 4
  consider_home: 24    
  new_device_defaults:
    track_new_devices: false
    hide_if_away: false