- platform: mqtt
  name: "Office Ceiling Light"
  state_topic: "stat/officelight/POWER"
  command_topic: "cmnd/officelight/POWER"
  availability_topic: "tele/officelight/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
