##Office
- platform: mqtt
  name: "Office Ceiling Light"
  state_topic: "office/officelight/stat/POWER1"
  command_topic: "office/officelight/cmnd/POWER"
  availability_topic: "office/officelight/tele/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: mqtt
  name: "Office Desk Light"
  state_topic: "office/officelight-desk/stat/POWER"
  command_topic: "office/officelight-desk/cmnd/POWER"
  availability_topic: "office/officelight-desk/tele/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: mqtt
  name: "3d Printer Led"
  state_topic: "office/3dprinter_led/stat/POWER"
  command_topic: "office/3dprinter_led/cmnd/POWER"
  #brightness_state_topic: "008565AA/rgb/brightness/status"
  #brightness_command_topic: "008565AA/rgb/brightness/set"
  rgb_state_topic: "office/3dprinter_led/stat/color"
  rgb_command_topic: "office/3dprinter_led/cmnd/color"
  state_value_template: "{{ value_json.state }}"
  brightness_command_topic: "office/3dprinter_led/cmnd/DIMMER"
  brightness_state_topic: "office/3dprinter_led/stat/RESULT"
  brightness_value_template: "{{ value_json.Dimmer }}"
  rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  brightness: true
  rgb: true


- platform: mqtt
  name: "Office Lego Light"
  state_topic: "office/ledlight/stat/POWER"
  command_topic: "office/ledlight/cmnd/POWER"
  qos: 1
  retain: true
  payload_on: "ON"
  payload_off: "OFF"
  brightness_scale: 100
  brightness_command_topic: "office/ledlight/cmnd/DIMMER"
  brightness_state_topic: "office/ledlight/stat/RESULT"
  brightness_value_template: "{{ value_json.Dimmer }}"
  rgb_command_topic: "office/ledlight/cmnd/COLOR"
  rgb_command_template: "{{ '%02x%02x%02x' | format(red, green, blue)}}"
  rgb_state_topic: "office/ledlight/stat/RESULT"
  rgb_value_template: "{{ value_json.Color[0:2] | int(base=16) }},{{ value_json.Color[2:4] | int(base=16) }},{{ value_json.Color[4:6] | int(base=16) }}"

- platform: mqtt
  name: "Nursery BedLight"
  state_topic: "nursery/nursery-bedlight/stat/POWER"
  command_topic: "nursery/nursery-bedlight/cmnd/POWER"
  qos: 1
  retain: true
  payload_on: "ON"
  payload_off: "OFF"
  brightness_scale: 100
  brightness_command_topic: "nursery/nursery-bedlight/cmnd/DIMMER"
  brightness_state_topic: "nursery/nursery-bedlight/stat/RESULT"
  brightness_value_template: "{{ value_json.Dimmer }}"
  rgb_command_topic: "nursery/nursery-bedlight/cmnd/COLOR"
  rgb_command_template: "{{ '%02x%02x%02x' | format(red, green, blue)}}" 
  rgb_state_topic: "nursery/nursery-bedlight/stat/RESULT"
  rgb_value_template: "{{ value_json.Color[0:2] | int(base=16) }},{{ value_json.Color[2:4] | int(base=16) }},{{ value_json.Color[4:6] | int(base=16) }}"

##LivingRoom
- platform: mqtt
  name: "Living Room Cabinet"
  state_topic: "livingroom/livingroom-cabinet/stat/POWER"
  command_topic: "livingroom/livingroom-cabinet/cmnd/POWER"
  availability_topic: "livingroom/livingroom-cabinet/tele/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
##Yeelight
