- platform: broadlink
  name: broadlink_Office_TV
  host: 192.168.88.200
  mac: '34:ea:34:42:a6:b2'
  ircodes_ini: 'includes/ircodes/hisense_officeTv.ini'
  ping_host: 192.168.88.155
  hidden: true
- platform: cast
  host: 192.168.88.150
- platform: cast
  host: 192.168.88.156
  #host: chromecast-maintv
- platform: cast
  host: 192.168.88.155
  hidden: true
  name: Chromecast Office Tv
- platform: kodi
  name: Kodi office
  host: 192.168.88.157
  turn_on_action:
  - service: media_player.kodi_call_method
    data:
      entity_id: media_player.kodi_office
      method: Addons.ExecuteAddon
      addonid: script.json-cec
      params:
        command: activate
  turn_off_action:
  - service: media_player.media_stop
    data:
      entity_id: media_player.kodi_office
  - service: media_player.kodi_call_method
    data:
      entity_id: media_player.kodi_office
      method: Addons.ExecuteAddon
      addonid: script.json-cec
      params:
        command: standby
  - service: script.turn_on
    data:
        entity_id: script.turnofftv
- platform: universal
  name: Office-TV
  children:
    - media_player.office_tv
    - media_player.kodi_office
  commands:
    turn_on:
      service: script.turn_on
      entity_id: script.turnontv
    turn_off:
      service: script.turn_on
      entity_id: script.turnofftv
    select_source:
      service: media_player.select_source
      data_template:
        entity_id: media_player.broadlink_office_tv
        source: '{{ source }}'
    volume_mute:
      service: media_player.volume_mute
      data:
        entity_id: switch.broadlink_office_tv
  attributes:
    source_list: media_player.broadlink_office_tv|source_list


