- platform: speedtest
  minute:
    - 0
    - 30
  monitored_conditions:
    - download
    - upload
    
- platform: dnsip
  name: dnsip
  hostname: !secret dnsHostName
  resolver: 8.8.8.8
- platform: mqtt
  state_topic: "office/office_sensor/temperature"
  name: "Temperatura Office"
  qos: 0
  unit_of_measurement: "°C"
- platform: mqtt
  state_topic: "office/office_sensor/humidity"
  name: "Humidade Office"
  qos: 0
  unit_of_measurement: "%"
- platform: cert_expiry
  host: !secret dnsHostName
  name: "SSL"
- platform: seventeentrack
  username: !secret seventeentrack_usr
  password: !secret seventeentrack_pwd 
#- platform: travisci
#  api_key: !secret travis_api
- platform: mqtt
  state_topic: "nursery/nursery_sensor/tele/SENSOR"
  value_template: "{{ value_json.BMP280.Temperature }}"
  name: "Temperatura Quarto Madalena"
  qos: 0
  unit_of_measurement: "°C"
- platform: mqtt
  state_topic: "garage/moto/fuelio"
  value_template: "{{ value_json.Odomentro }}"
  name: "Odometro Moto"
  qos: 0
  unit_of_measurement: "Km"
- platform: mqtt
  state_topic: "garage/moto/fuelio"
  value_template: "{{ value_json.L100km }}"
  name: "Consumo Moto"
  qos: 0
  unit_of_measurement: "L/100 km"