- platform: broadlink
  host: 192.198.88.200
  mac: '34:EA:34:42:A6:B2'
  type: rm_mini
  
  
- platform: mqtt
  name: "Christmas Lights"
  state_topic: "stat/livingroom-christmaslights/POWER"
  command_topic: "cmnd/livingroom-christmaslights/POWER"
  availability_topic: "tele/livingroom-christmaslights/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
  
- platform: mqtt
  name: "Remote Switch"
  state_topic: "stat/remoteSwitch/POWER"
  command_topic: "cmnd/remoteSwitch/POWER"
  availability_topic: "tele/remoteSwitch/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true