- platform: mqtt
  name: "Christmas Lights"
  state_topic: "livingroom/livingroom-christmaslights/stat/POWER"
  command_topic: "livingroom/livingroom-christmaslights/cmnd/POWER"
  availability_topic: "livingroom/livingroom-christmaslights/tele/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
  
- platform: mqtt
  name: "Remote Switch"
  state_topic: "office/remoteSwitch/stat/POWER"
  command_topic: "office/remoteSwitch/cmnd/POWER"
  availability_topic: "office/remoteSwitch/tele/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true